### ISSUE TITLE
Unable to install packages after installing pip in PyCharm

### ISSUE THREAD

**Issue by Bala88** [locationlabs/mockredis#102]
Hi.. I am a newbie.. I have installed PyCharm and Python 3.4. Interpreter was set and upgraded to pip to the latest version. Now I am unable to add any package from the repository. Am getting the below error. 

"  Collecting unittest2
  Could not fetch URL https://pypi.python.org/simple/unittest2/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600) - skipping

**  Could not find a version that satisfies the requirement unittest2 (from versions: )
No matching distribution found for unittest2 "**

**Comment by wheremiah** [comment]
I don't think this issue is related to mockredis.

I would suggest checking the url you have above:  https://pypi.python.org/simple/unittest2/ in a browser.  If that also shows an error you may be having a problem connecting to the correct server.  If that does not have an error, I'd look into your pypi config.
